name: Generate Snake

on:
  schedule:
    - cron: "0 20 * * *"  # 每天运行一次
  push:
    branches:
      - master
  workflow_dispatch: # 手动触发

jobs:
  generate:
    name: generate snake grid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate snake grid
        uses: Platane/snk/svg-only@v2.2.1
        with:
          github_user_name: <hhhhhhjs>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: .github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
